# Site settings
title: dpark's wiki
url: "https://dp44rk.github.io/"
baseurl: ""
description: >
    dpark's public Archive

# My information
email: dp4rk02@gmail.com
author: dpark
profile: 유물론자
twitter_username: sample-value
github_username: dp44rk
comment-support: utterances

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist

permalink: /blog/:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

paginate: 10
paginator_path: "/blog"
paginate_path: "/blog/page:num/"

# Collections
collections:
    wiki:
        output: true
        permalink: /:collection/:path/

# Comment Service
giscus:
  repo: dp44rk/dp44rk.github.io
  repo_id: R_kgDOOAeUhQ
  category: Announcements
  category_id: DIC_kwDOOAeUhc4CnZXW

google_analytics:
  ua: G-HDC27S52KD
  encrypted_ua: U2FsdGVkX19xJBnOu2mMLJ06PgI5MupZDm+8ZlOl7fQ=

google_adsense:
  client: SAMPLE-VALUE

blame: "https://github.com/dp44rk/dp44rk.github.io/blame/master/_wiki"
edit: "https://github.com/dp44rk/dp44rk.github.io/edit/master/_wiki"
issue: "https://github.com/dp44rk/dp44rk.github.ioo/issues/new"

timezone: "Asia/Seoul"

# https://kramdown.gettalong.org/rdoc/Kramdown/Options.html - smart_quotes
kramdown:
    smart_quotes: ["apos", "apos", "quot", "quot"]
